### ISSUE TITLE
Prompt for remaining alters from last visit

### ISSUE THREAD

**Issue by pfsj** [pfsj/radar-protocol#2]
A prompt should appear when alters from previous visits cannot all be seen on the screen and trying to move past the name generator. We're working on a draft of this and will send soon.

**Comment by pfsj** [comment]
Here is what we were thinking for this screen (see below). Again, the main function of this page would be dragging additional alters into the black space on the right and the same thing happens as if you did it in the first step (i.e., relationship roles pops up and they get added as a node following closing of the relationship screen). This screen would remain up after adding each node until the participant clicks "Close". During this time they would also be unable to move forward using the arrow "next page" button (i.e., they have to click "Close" to proceed. Let me know if you have questions/thoughts. 

![remainingalterprompt](https://cloud.githubusercontent.com/assets/10948594/7892327/1bd8ed04-0619-11e5-942e-01e826474029.jpg)

**Comment by jthrilly** [comment]
above a threshold of remaining alters we expand the bubble to prompt before moving on

(just a note for me...will respond next week)
